/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhpdc.lab1.gui;

import com.thanhpdc.lab1.dao.UserDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Cong Thanh
 */
public class CreateFrame extends javax.swing.JDialog {

    LoginFrame loginFormm;
    String regex = "^[a-zA-Z0-9 ]+$";

    /**
     * Creates new form CreateFrame
     */
    public CreateFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("create new account");
        this.setLocationRelativeTo(null);
        if (!parent.isActive()) {
            JOptionPane.showMessageDialog(null, "Please login before using");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblUserID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        rdoAdmin = new javax.swing.JRadioButton();
        rdoUser = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        lblNameWarnning = new javax.swing.JLabel();
        lblCodeWarnning = new javax.swing.JLabel();
        lblPasswordWarnning = new javax.swing.JLabel();
        lblRoleWarnning = new javax.swing.JLabel();
        lblConfirmWarnning = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblUserID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblUserID.setText("Your ID");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblName.setText("Your Name");

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPassword.setText("Your Password");

        lblConfirm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblConfirm.setText("Your Confirm");

        lblRole.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblRole.setText("Your Role");

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 204));
        jLabel6.setText("Create form");

        txtCode.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        rdoAdmin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoAdmin.setText("Admin");

        rdoUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rdoUser.setText("User");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 0, 0));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblNameWarnning.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lblNameWarnning.setForeground(new java.awt.Color(255, 0, 0));

        lblCodeWarnning.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lblCodeWarnning.setForeground(new java.awt.Color(255, 0, 0));

        lblPasswordWarnning.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lblPasswordWarnning.setForeground(new java.awt.Color(255, 0, 0));

        lblRoleWarnning.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lblRoleWarnning.setForeground(new java.awt.Color(255, 0, 0));

        lblConfirmWarnning.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lblConfirmWarnning.setForeground(new java.awt.Color(255, 0, 0));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtConfirm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblRole)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoAdmin)
                                    .addGap(51, 51, 51)
                                    .addComponent(rdoUser)
                                    .addGap(122, 122, 122))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCodeWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblNameWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 20, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblConfirm))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRoleWarnning, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(lblConfirmWarnning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPasswordWarnning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodeWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasswordWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirm)
                    .addComponent(txtConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirmWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRole)
                            .addComponent(rdoAdmin)
                            .addComponent(rdoUser))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblRoleWarnning, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        lblCodeWarnning.setText("");
        lblNameWarnning.setText("");
        lblPasswordWarnning.setText("");
        lblConfirmWarnning.setText("");
        lblRoleWarnning.setText("");

        String code = txtCode.getText().trim();
        String name = txtName.getText().trim();
        String password = txtPassword.getText().trim();
        String confirm = txtConfirm.getText().trim();
        if (code.isEmpty() || name.isEmpty() || password.isEmpty() || confirm.isEmpty() || (!rdoAdmin.isSelected() && !rdoUser.isSelected())) {
            if (code.isEmpty()) {
                lblCodeWarnning.setText("Please input your code  ");
            }
            if (name.isEmpty()) {
                lblNameWarnning.setText("Please input your name  ");
            }
            if (password.isEmpty()) {
                lblPasswordWarnning.setText("Please input your password  ");
            }
            if (confirm.isEmpty()) {
                lblConfirmWarnning.setText("Please confirm your password  ");
            }
            if (!rdoAdmin.isSelected() && !rdoUser.isSelected()) {
                lblRoleWarnning.setText("Please choose your role  ");
            }
        } else {
            if (!code.matches(regex) || !name.matches(regex) || !password.matches(regex) || !confirm.matches(regex)) {
                if (!code.matches(regex)) {
                    lblCodeWarnning.setText("Your input code is invalid  ");
                }
                if (!name.matches(regex)) {
                    lblNameWarnning.setText("Your input name is invalid  ");
                }
                if (!password.matches(regex)) {
                    lblPasswordWarnning.setText("Your input password is invalid  ");
                }
                if (!confirm.matches(regex)) {
                    lblConfirmWarnning.setText("Your confirm password is invalid  ");
                }
            } else {
                if (UserDAO.checkUserID(code)) {
                    lblCodeWarnning.setText("Your input code is already exist  ");
                    txtCode.setText("");
                } else {
                    if (!password.equals(confirm)) {
                        lblPasswordWarnning.setText("Your password and confirm is not match  ");
                        lblConfirmWarnning.setText("Your password and confirm is not match  ");
                    } else {
                        try {
                            UserDAO.addUser(code, name, password, rdoAdmin.isSelected());
                            JOptionPane.showMessageDialog(null, "Create account successfully");
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex.toString());
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateFrame dialog = new CreateFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCodeWarnning;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblConfirmWarnning;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameWarnning;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordWarnning;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRoleWarnning;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoUser;
    private javax.swing.JTextField txtCode;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
